name: CI Checks
on: [push, pull_request]

jobs:
  Checks:
    runs-on: ${{ matrix.os }}
    env:
      BRANCH_NAME: ${{GITHUB_REF#refs/*/}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${BRANCH_NAME})"
        id: extract_branch
      - name: Setup Nx Cloud variables
        run: echo "branch name ${steps.extract_branch.outputs.branch}"
        env:  
          NX_BRANCH: ${{ github.event.number || steps.extract_branch.outputs.branch }}
          NX_RUN_GROUP: ${{ github.run_id }}
      - run: echo ${{env.NX_BRANCH}}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn nx run-many --all --parallel --target=lint
      - name: Test
        run: yarn nx run-many --all --parallel --target=test
      - name: Build
        run: yarn nx run-many --all --parallel --target=build