name: CI Checks
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get origin master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: $GITHUB_WORKSPACE/github-actions/node_modules
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
  lint:
    runs-on: ubuntu-latest

    needs: [setup]
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get origin master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: $GITHUB_WORKSPACE/github-actions/node_modules
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-
      - run: yarn affected:lint --base=origin/master~1 --head=$GITHUB_SHA

  build:
    runs-on: ubuntu-latest

    needs: [setup]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get origin master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: $GITHUB_WORKSPACE/github-actions/node_modules
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-
      - run: yarn affected:build --base=origin/master~1 --head=$GITHUB_SHA

  test:
    runs-on: ubuntu-latest

    needs: [setup]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get origin master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: $GITHUB_WORKSPACE
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-
      - run: yarn affected:test --base=origin/master~1 --head=$GITHUB_SHA
