name: CI Checks
on: [push, pull_request]
jobs:
  Checks:
    env:
      NX_BRANCH: ${{ github.event.number || 'master' }}
      NX_RUN_GROUP: ${{ github.run_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
      - run: echo "${{env.NX_BRANCH}}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2